//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BME_G0X.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BME_G0TYPE                  129
#define IDD_CONFIGURATION_TABLE         130
#define IDD_DEFINE_DELAY_GENERATOR      131
#define IDR_STANDARD_ICON               133
#define IDD_TIME_SEQUENCE               134
#define IDD_EDIT_PARAMETERS             135
#define IDD_PARAMETER_ROUTINE           136
#define IDD_G05_MASTER                  137
#define IDD_G05_SLAVE                   138
#define IDD_REPLACE_LINE                139
#define IDD_FILE_OPTIONS                140
#define IDD_G02P3_MASTER                141
#define IDD_G05P2_MASTER                142
#define IDD_DONE_SELECT                 143
#define IDD_G05P4_MASTER                144
#define IDD_TIME_LIST                   145
#define IDD_INSERT_LINE                 157
#define IDD_G04_MASTER                  275
#define IDD_G04_SLAVE                   276
#define IDD_G03_MASTER                  277
#define IDD_G02_MASTER                  278
#define IDD_G02_SLAVE                   279
#define IDD_G03_SLAVE                   280
#define IDC_DG_ADDRESS                  1000
#define IDC_DG_MASTER                   1001
#define IDC_DELGEN_TABLE                1002
#define IDC_INTERNAL                    1002
#define IDC_DG_BUS                      1002
#define IDC_EXTERNAL                    1003
#define IDC_TRIGGER_PERIOD              1004
#define IDC_RISING                      1005
#define IDC_FALLING                     1006
#define IDC_REPLACE_LINE                1007
#define IDC_STOP_ON_PRESET              1007
#define IDC_INSERT_LINE                 1008
#define IDC_PRESET_VALUE                1008
#define IDC_TRIGGER_COUNT               1009
#define IDC_RESET_COUNTER               1010
#define IDC_DESIGNATOR                  1011
#define IDC_CALIBRATE_TIMING            1012
#define IDC_READ_TRIGGERS               1013
#define IDC_ARM_BY_INTERNAL             1014
#define IDC_DG_PRESCALER                1015
#define IDC_T0_NAME                     1016
#define IDC_A_NAME                      1017
#define IDC_B_NAME                      1018
#define IDC_INSERT_BEFORE               1019
#define IDC_T0_POSITIVE                 1019
#define IDC_D_NAME2                     1019
#define IDC_INSERT_AFTER                1020
#define IDC_T0_NEGATIVE                 1020
#define IDC_E_NAME2                     1020
#define IDC_A_POSITIVE                  1021
#define IDC_F_NAME2                     1021
#define IDC_A_NEGATIVE                  1022
#define IDC_B_POSITIVE                  1023
#define IDC_B_NEGATIVE                  1024
#define IDC_T0_TERMINATE                1025
#define IDC_A_TERMINATE                 1026
#define IDC_B_TERMINATE                 1027
#define IDC_TRIGGER_TERMINATE           1028
#define IDC_DG_NAME                     1029
#define IDC_CRYSTAL_OSCILLATOR          1030
#define IDC_TRIGGER_INPUT               1031
#define IDC_C_NAME                      1032
#define IDC_GATE_DIVIDER                1033
#define IDC_C_POSITIVE                  1033
#define IDC_TRIGGER_LEVEL               1034
#define IDC_C_NEGATIVE                  1034
#define IDC_GATE_POSITIVE               1035
#define IDC_D_NAME                      1035
#define IDC_GATE_NEGATIVE               1036
#define IDC_D_POSITIVE                  1036
#define IDC_T0_HIGH_DRIVE               1037
#define IDC_A_HIGH_DRIVE                1038
#define IDC_B_HIGH_DRIVE                1039
#define IDC_TTL_LEVEL                   1040
#define IDC_NIM_LEVEL                   1041
#define IDC_ECL_LEVEL                   1042
#define IDC_TIME_PER_STEP               1043
#define IDC_D_NEGATIVE                  1043
#define IDC_MODULO_T0                   1044
#define IDC_E_NAME                      1044
#define IDC_MODULO_A                    1045
#define IDC_E_POSITIVE                  1045
#define IDC_MODULO_B                    1046
#define IDC_E_NEGATIVE                  1046
#define IDC_MODULO_D                    1047
#define IDC_F_NAME                      1047
#define IDC_ZERO_MODULO                 1048
#define IDC_F_POSITIVE                  1048
#define IDC_MODULO_E                    1049
#define IDC_F_NEGATIVE                  1049
#define IDC_ACTIVATE_T0                 1050
#define IDC_MODULO_F                    1050
#define IDC_C_TERMINATE                 1050
#define IDC_ACTIVATE_A                  1051
#define IDC_VALID_DIGITS                1051
#define IDC_CALIBRATION_PATH            1051
#define IDC_D_TERMINATE                 1051
#define IDC_ACTIVATE_B                  1052
#define IDC_TRIGGER_DIVIDER             1052
#define IDC_GATE_AB                     1053
#define IDC_FREE_RUNNING                1053
#define IDC_DETECT_PCI                  1054
#define IDC_GATE_CD                     1054
#define IDC_E_TERMINATE                 1054
#define IDC_ADDRESS_LINE                1055
#define IDC_GATE_EF                     1055
#define IDC_PULSE_WIDTH                 1056
#define IDC_BROWSE                      1057
#define IDC_F_TERMINATE                 1057
#define IDC_CALIBRATE_OFFSET            1058
#define IDC_FT_ACTIVATE_T0              1061
#define IDC_FT_ACTIVATE_A               1062
#define IDC_ERASE_LIST                  1063
#define IDC_FT_ACTIVATE_B               1063
#define IDC_IGNORE                      1065
#define IDC_MEMORIZE                    1066
#define IDC_FORCE_TRIGGER               1067
#define IDC_INHIBIT_TRIGGER             1068
#define IDC_PRIMARY_GO                  1075
#define IDC_SECONDARY_GO                1076
#define IDC_FORCE_GO                    1077
#define IDC_OFFSET_T0                   1078
#define IDC_OFFSET_A                    1079
#define IDC_OFFSET_B                    1080
#define IDC_GATE_XOR                    1081
#define IDC_GATE_OR                     1082
#define IDC_GATE_AND                    1083
#define IDC_OFFSET_D                    1084
#define IDC_ACKNOWLEDGE_NONE            1085
#define IDC_OFFSET_E                    1085
#define IDC_ACKNOWLEDGE_DEFAULT         1086
#define IDC_OFFSET_F                    1086
#define IDC_ACKNOWLEDGE_CUSTOM          1087
#define IDC_PRIMARY_T0                  1088
#define IDC_PRIMARY_A                   1089
#define IDC_PRIMARY_B                   1090
#define IDC_SECONDARY_T0                1091
#define IDC_SECONDARY_A                 1092
#define IDC_SECONDARY_B                 1093
#define IDC_FORCE_T0                    1094
#define IDC_FORCE_A                     1095
#define IDC_FORCE_B                     1096
#define IDC_DONE_PRIMARY_T0             1097
#define IDC_DONE_PRIMARY_A              1098
#define IDC_DONE_PRIMARY_B              1099
#define IDC_DONE_SECONDARY_T0           1100
#define IDC_DONE_SECONDARY_A            1101
#define IDC_DONE_SECONDARY_B            1102
#define IDC_DONE_FORCE_T0               1103
#define IDC_DONE_FORCE_A                1104
#define IDC_DONE_FORCE_B                1105
#define IDC_DONE_MSB_T0                 1106
#define IDC_DELAY_T0                    1107
#define IDC_DONE_MSB_A                  1107
#define IDC_DELAY_A                     1108
#define IDC_DONE_MSB_B                  1108
#define IDC_DELAY_B                     1109
#define IDC_SET_BACK_T0                 1110
#define IDC_MS_BUS_T0                   1110
#define IDC_SET_BACK_A                  1111
#define IDC_MS_BUS_A                    1111
#define IDC_SET_BACK_B                  1112
#define IDC_MS_BUS_B                    1112
#define IDC_REMOVE_DELAY_GENERATOR      1113
#define IDC_FIRE_SECOND_T0              1113
#define IDC_MS_BUS_CLOCK                1113
#define IDC_DELAY_D                     1113
#define IDC_DEFINE_DELAY_GENERATOR      1114
#define IDC_FIRE_SECOND_A               1114
#define IDC_PERIOD_NAME                 1114
#define IDC_DELAY_E                     1114
#define IDC_FIRE_SECOND_B               1115
#define IDC_T0_CLOCK                    1115
#define IDC_DELAY_F                     1115
#define IDC_RESYNCH                     1116
#define IDC_WIDTH_A                     1116
#define IDC_T0_DELAY_CLOCK              1117
#define IDC_WIDTH_B                     1117
#define IDC_INHIBIT_T0                  1118
#define IDC_A_DELAY_CLOCK               1118
#define IDC_INHIBIT_A                   1119
#define IDC_B_DELAY_CLOCK               1119
#define IDC_INHIBIT_B                   1120
#define IDC_WIDTH_D                     1121
#define IDC_DELAY_C                     1122
#define IDC_MODULO_C                    1123
#define IDC_OFFSET_C                    1124
#define IDC_WIDTH_C                     1125
#define IDC_WIDTH_E                     1126
#define IDC_DG_TYPE                     1127
#define IDC_WIDTH_F                     1127
#define IDC_AB_XOR                      1134
#define IDC_AB_OR                       1135
#define IDC_AB_AND                      1136
#define IDC_CD_XOR                      1137
#define IDC_CD_OR                       1138
#define IDC_CD_AND                      1139
#define IDC_EF_XOR                      1140
#define IDC_EF_OR                       1141
#define IDC_EF_AND                      1142
#define IDC_PRIMARY_LOCAL_A             1143
#define IDC_PRIMARY_LOCAL_B             1144
#define IDC_PRIMARY_LOCAL_C             1145
#define IDC_SECONDARY_LOCAL_A           1146
#define IDC_SECONDARY_LOCAL_B           1147
#define IDC_SECONDARY_LOCAL_C           1148
#define IDC_FORCE_LOCAL_A               1149
#define IDC_EDIT_PARAMETER              1150
#define IDC_FORCE_LOCAL_B               1150
#define IDC_EDIT_PARAMETER_LINE         1151
#define IDC_FORCE_LOCAL_C               1151
#define IDC_PRIMARY_BUS_A               1152
#define IDC_PRIMARY_BUS_B               1153
#define IDC_REMOVE_LINE                 1154
#define IDC_PRIMARY_BUS_C               1154
#define IDC_SECONDARY_BUS_A             1155
#define IDC_SECONDARY_BUS_B             1156
#define IDC_SECONDARY_BUS_C             1157
#define IDC_FORCE_BUS_A                 1158
#define IDC_FORCE_BUS_B                 1159
#define IDC_FORCE_BUS_C                 1160
#define IDC_PRIMARY_LOCAL_D             1161
#define IDC_PRIMARY_LOCAL_E             1162
#define IDC_PRIMARY_LOCAL_F             1163
#define IDC_SECONDARY_LOCAL_D           1164
#define IDC_ONCE                        1165
#define IDC_SECONDARY_LOCAL_E           1165
#define IDC_CONTINUOUSLY                1166
#define IDC_SECONDARY_LOCAL_F           1166
#define IDC_UPWARDS                     1167
#define IDC_FORCE_LOCAL_D               1167
#define IDC_DOWNWARDS                   1168
#define IDC_FORCE_LOCAL_E               1168
#define IDC_UP_AND_DOWN                 1169
#define IDC_FORCE_LOCAL_F               1169
#define IDC_PRIMARY_BUS_D               1170
#define IDC_DOWN_AND_UP                 1171
#define IDC_PRIMARY_BUS_E               1171
#define IDC_X_PARAMETER_DEFINE          1172
#define IDC_PRIMARY_BUS_F               1172
#define IDC_X_PARAMETER_LIST            1173
#define IDC_SECONDARY_BUS_D             1173
#define IDC_LAST_POINT                  1174
#define IDC_SECONDARY_BUS_E             1174
#define IDC_SECONDARY_BUS_F             1175
#define IDC_NO_STEPS                    1176
#define IDC_FORCE_BUS_D                 1176
#define IDC_FIRST_POINT                 1177
#define IDC_FORCE_BUS_E                 1177
#define IDC_CALCULATE_SEQUENCE          1178
#define IDC_FORCE_BUS_F                 1178
#define IDC_NEW_COLUMN                  1179
#define IDC_INHIBIT_C                   1179
#define IDC_INSERT_COLUMN               1180
#define IDC_INHIBIT_D                   1180
#define IDC_COLUMN_NO                   1181
#define IDC_INHIBIT_E                   1181
#define IDC_INHIBIT_F                   1182
#define IDC_E_ENA_A                     1183
#define IDC_E_ENA_B                     1184
#define IDC_E_ENA_C                     1185
#define IDC_E_ENA_D                     1186
#define IDC_E_ENA_E                     1187
#define IDC_E_ENA_F                     1188
#define IDC_F_ENA_A                     1189
#define IDC_F_ENA_B                     1190
#define IDC_F_ENA_C                     1191
#define IDC_F_ENA_D                     1192
#define IDC_F_ENA_E                     1193
#define IDC_F_ENA_F                     1194
#define IDC_BUS_ENA_A                   1195
#define IDC_BUS_ENA_B                   1196
#define IDC_BUS_ENA_C                   1197
#define IDC_BUS_ENA_D                   1198
#define IDC_BUS_ENA_E                   1199
#define IDC_BUS_ENA_F                   1200
#define IDC_GATE_LEVEL                  1201
#define IDC_BURST                       1203
#define IDC_E_DISCONNECT                1204
#define IDC_F_DISCONNECT                1205
#define IDC_E_INPUT_P                   1206
#define IDC_F_INPUT_P                   1207
#define IDC_GATE_DELAY                  1208
#define IDC_STBK_LOC_A                  1209
#define IDC_STBK_LOC_B                  1210
#define IDC_STBK_LOC_C                  1211
#define IDC_STBK_LOC_D                  1212
#define IDC_STBK_LOC_E                  1213
#define IDC_STBK_LOC_F                  1214
#define IDC_STBK_BUS_A                  1215
#define IDC_STBK_BUS_B                  1216
#define IDC_STBK_BUS_C                  1217
#define IDC_STBK_BUS_D                  1218
#define IDC_STBK_BUS_E                  1219
#define IDC_STBK_BUS_F                  1220
#define IDC_START_LOC_A                 1221
#define IDC_START_LOC_B                 1222
#define IDC_START_LOC_C                 1223
#define IDC_START_LOC_D                 1224
#define IDC_START_LOC_E                 1225
#define IDC_START_LOC_F                 1226
#define IDC_START_BUS_A                 1227
#define IDC_START_BUS_B                 1228
#define IDC_START_BUS_C                 1229
#define IDC_START_BUS_D                 1230
#define IDC_START_BUS_E                 1231
#define IDC_START_BUS_F                 1232
#define IDC_STEP_BACK                   1233
#define IDC_STBK_REF_A                  1234
#define IDC_STBK_REF_B                  1235
#define IDC_FPGA_MEMORY_LIST            1235
#define IDC_STBK_REF_C                  1236
#define IDC_E_INPUT_N                   1236
#define IDC_STBK_REF_D                  1237
#define IDC_F_INPUT_N                   1237
#define IDC_STBK_REF_E                  1238
#define IDC_E_MS_BUS                    1238
#define IDC_STBK_REF_F                  1239
#define IDC_F_MS_BUS                    1239
#define IDC_TRIGGER_MULTIPLIER          1240
#define IDC_GATE_TERMINATE              1241
#define IDC_JUMP_START                  1242
#define IDC_EXT_FREQUENCY               1243
#define IDC_SYNCHRONIZE_GATE            1244
#define IDC_READ_FILE                   1245
#define IDC_SAVE_FILE                   1246
#define IDC_APPLY                       1312
#define IDC_REMOVE_COLUMN               1599
#define IDC_PARAMETER_STEP_SIZE         1665
#define IDC_MAX_NO_DATASETS             1813
#define ID_CONFIGURE                    32771
#define ID_DEFINE                       32772
#define ID_ACTIVATE                     32773
#define ID_DEACTIVATE                   32774
#define ID_DELAY                        32775
#define ID_TIME_SEQUENCE                32776
#define ID_FILE_OPTIONS                 32777
#define ID_SAVE_STATE                   32778
#define ID_TIME_LIST                    32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1247
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
